refactor: adjust all dialogs to use oak components
oaknational/oak-ai-lesson-assistant pull request #335
Opened 2024-11-04 10:57 UTC by tomwisecodes

## Description
 
changes text on share page
adjusts all dialogs to use oak components for styling

Follow up discussion. 
Should we move away from radix to manage the dialog? 

https://www.notion.so/oaknationalacademy/Share-disclaimer-copy-update-9b8673eac6cb440bb314223547df97d4

2024-11-05 10:16 UTC, mantagen approved these changes
Code looks good!

2024-11-05 10:16 UTC, mantagen commented on apps/nextjs/src/components/AppComponents/Chat/Chat/types.ts
>    | ""
what's that dialog type?

2024-11-05 10:16 UTC, mantagen commented on apps/nextjs/src/components/DialogControl/DialogContents.tsx
> +const dialogTitlesAndIcons: Record<
Was gonna comment here but you already made the change!

2024-11-12 16:34 UTC, mikeritson-oak requested changes
I’ve added some testing notes to the top of the feedback and share modal tickets in Notion.

2024-11-13 13:27 UTC, mikeritson-oak requested changes
Rechecked for updates, mostly look OK but two minor amendments needed in the share modal. Also, some updates were also noted in the feedback Notion ticket.

2024-11-19 13:43 UTC, mikeritson-oak approved these changes
All looking good for a release to production now. Minor issues or design changes can be picked up in later tickets. 👍

2024-11-19 13:46 UTC, merged

2024-11-21 10:19 UTC, oak-machine-user commented
:tada: This PR is included in version 1.16.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/oak-ai-lesson-assistant/releases/tag/v1.16.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: