chore: test build
oaknational/oak-ai-lesson-assistant pull request #375
Opened 2024-11-21 09:30 UTC by tomwisecodes

## Description
test build of main

2024-11-21 13:22 UTC, mantagen reviewed
Looks good - few comments/suggestions

2024-11-21 13:46 UTC, tomwisecodes commented on apps/nextjs/src/components/DialogControl/ContentOptions/ClearSingleChatFromChatHistory.tsx
> +    trpc.chat.appSessions.deleteChatById.useMutation({
Lets do that has a follow up

2024-11-21 13:50 UTC, tomwisecodes commented on apps/nextjs/src/components/AppComponents/Chat/sidebar-items.tsx
> +      isThisWeek(chat.updatedAt, { weekStartsOn: 1 }) &&
lets leave for now

2024-11-21 14:12 UTC, mantagen commented on apps/nextjs/src/components/AppComponents/Chat/Chat/types.ts
> +  | "clear-single-chat";
🤦

2024-11-21 14:12 UTC, mantagen approved these changes
Code looks good!

2024-11-22 11:50 UTC, mikeritson-oak requested changes
Reviewed again and details within the Notion ticket for findings.

2024-11-26 11:35 UTC, mikeritson-oak approved these changes
These changes have been reviewed and confirmed. We have a couple of minor follow-up items to raise in separate tickets. 👍

2024-11-26 11:57 UTC, merged

2024-11-28 12:44 UTC, oak-machine-user commented
:tada: This PR is included in version 1.17.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/oak-ai-lesson-assistant/releases/tag/v1.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: